os: osx
language: swift
osx_image: xcode12
podfile: Example/Podfile
xcode_workspace: Example/Monri.xcworkspace # path to your xcworkspace folder
xcode_scheme: Monri-Example
# { platform:iOS Simulator, id:D80C2627-E44F-4F40-8853-F8A7FDCDCF74, OS:12.4, name:iPad (5th generation) }
# 		{ platform:iOS Simulator, id:4A33CFB7-99A7-4B5D-9C5E-9D2BFC794ABE, OS:12.4, name:iPad (6th generation) }
# 		{ platform:iOS Simulator, id:3CFF6F55-8E37-4429-8673-9EE4A06AB1FB, OS:13.2.2, name:iPad (7th generation) }
# 		{ platform:iOS Simulator, id:554CC3C8-3267-4A00-843C-FEA8D7B848EE, OS:13.3, name:iPad (7th generation) }
# 		{ platform:iOS Simulator, id:B6E0E0BD-3DF5-4D41-86B1-1C972F1D6914, OS:13.4, name:iPad (7th generation) }
# 		{ platform:iOS Simulator, id:A83B4AE4-7587-45EB-9700-B6B55F6800E9, OS:13.5, name:iPad (7th generation) }
# 		{ platform:iOS Simulator, id:DA072705-DFB8-4085-8D53-CE992F346B28, OS:12.4, name:iPad Air }
# 		{ platform:iOS Simulator, id:D9A2F747-FB34-4ACB-9986-CE11CD2DF399, OS:12.4, name:iPad Air (3rd generation) }
# 		{ platform:iOS Simulator, id:B0F3EB2E-A32F-4BAE-8426-D71D077E165B, OS:13.0, name:iPad Air (3rd generation) }
# 		{ platform:iOS Simulator, id:D6A68B3C-07EB-406A-9EB7-0044CD03761A, OS:13.1, name:iPad Air (3rd generation) }
# 		{ platform:iOS Simulator, id:5C730A01-E0DF-462B-93C5-0B5FB560804A, OS:13.2.2, name:iPad Air (3rd generation) }
# 		{ platform:iOS Simulator, id:2F7FE00E-7304-409C-8B79-FF87A811D047, OS:13.3, name:iPad Air (3rd generation) }
# 		{ platform:iOS Simulator, id:012CF5A7-8B8A-464E-9219-B0C4EAE1BBB9, OS:13.4, name:iPad Air (3rd generation) }
# 		{ platform:iOS Simulator, id:6451C2FC-1A7A-41F0-AEAF-C2338522857E, OS:13.5, name:iPad Air (3rd generation) }
# 		{ platform:iOS Simulator, id:393AC9F6-1339-4C2A-BE48-A1A7527FBEF0, OS:12.4, name:iPad Air 2 }
# 		{ platform:iOS Simulator, id:D79F1739-8413-49FE-968B-DA784A4F6029, OS:12.4, name:iPad Pro (9.7-inch) }
# 		{ platform:iOS Simulator, id:8F4683B2-737C-47BF-AAF7-87DD1DCE473C, OS:13.0, name:iPad Pro (9.7-inch) }
# 		{ platform:iOS Simulator, id:CADE43FE-608E-4507-B227-6B416007D280, OS:13.1, name:iPad Pro (9.7-inch) }
# 		{ platform:iOS Simulator, id:7CD91B3F-1BFA-4288-8722-5732355F2BB3, OS:13.2.2, name:iPad Pro (9.7-inch) }
# 		{ platform:iOS Simulator, id:2453EA54-9F4B-48AA-B5B7-A90D78EF0752, OS:13.3, name:iPad Pro (9.7-inch) }
# 		{ platform:iOS Simulator, id:44A0D744-BF4C-4240-8E9E-FC6FA140063C, OS:13.4, name:iPad Pro (9.7-inch) }
# 		{ platform:iOS Simulator, id:58D5D702-1574-4186-BBB9-0627DCA90242, OS:13.5, name:iPad Pro (9.7-inch) }
# 		{ platform:iOS Simulator, id:A3AA88BC-98D6-472C-ADED-28418BF979EF, OS:14.0, name:iPad Pro (9.7-inch) }
# 		{ platform:iOS Simulator, id:0773CBE9-7C41-4E60-A262-C9C98F88E614, OS:12.4, name:iPad Pro (10.5-inch) }
# 		{ platform:iOS Simulator, id:B38AA57F-4420-445C-B44C-E1286E4BA540, OS:12.4, name:iPad Pro (11-inch) (1st generation) }
# 		{ platform:iOS Simulator, id:C05E0867-C269-4F20-8728-F54626E84C4A, OS:13.0, name:iPad Pro (11-inch) (1st generation) }
# 		{ platform:iOS Simulator, id:3EEAB422-B1C9-4522-A589-E782BE355C7B, OS:13.1, name:iPad Pro (11-inch) (1st generation) }
# 		{ platform:iOS Simulator, id:EF7D8037-E049-43EA-AE1E-385469905338, OS:13.2.2, name:iPad Pro (11-inch) (1st generation) }
# 		{ platform:iOS Simulator, id:9131413A-B650-4585-BA9B-0482FD8E35B2, OS:13.3, name:iPad Pro (11-inch) (1st generation) }
# 		{ platform:iOS Simulator, id:694B831E-8AED-491C-9807-2604C4C46EB5, OS:13.4, name:iPad Pro (11-inch) (2nd generation) }
# 		{ platform:iOS Simulator, id:7FDF2FFA-F5E1-4DFE-A907-559ED901DFC5, OS:13.5, name:iPad Pro (11-inch) (2nd generation) }
# 		{ platform:iOS Simulator, id:649DF535-1591-4E1B-A215-D497BFE66FEE, OS:14.0, name:iPad Pro (11-inch) (2nd generation) }
# 		{ platform:iOS Simulator, id:D667E833-54CF-4C5B-97F2-650658B0883E, OS:12.4, name:iPad Pro (12.9-inch) (1st generation) }
# 		{ platform:iOS Simulator, id:4BB3C918-C988-433C-9B63-D8B03E3F5F69, OS:12.4, name:iPad Pro (12.9-inch) (2nd generation) }
# 		{ platform:iOS Simulator, id:13658D76-2801-4C3C-8006-27339F602B56, OS:12.4, name:iPad Pro (12.9-inch) (3rd generation) }
# 		{ platform:iOS Simulator, id:5D147170-180A-4521-8366-7D3853AEAE23, OS:13.0, name:iPad Pro (12.9-inch) (3rd generation) }
# 		{ platform:iOS Simulator, id:DB80431B-8EA8-426A-9930-2028E045A59D, OS:13.1, name:iPad Pro (12.9-inch) (3rd generation) }
# 		{ platform:iOS Simulator, id:297E531F-7434-4EE5-87C3-E129DAA3262A, OS:13.2.2, name:iPad Pro (12.9-inch) (3rd generation) }
# 		{ platform:iOS Simulator, id:0743AE22-7522-4FD8-9D66-E7F57192C781, OS:13.3, name:iPad Pro (12.9-inch) (3rd generation) }
# 		{ platform:iOS Simulator, id:0EE267C3-BB37-412C-A2E1-A712174704DB, OS:13.4, name:iPad Pro (12.9-inch) (4th generation) }
# 		{ platform:iOS Simulator, id:4478EA56-A872-4562-8979-B414BF2A5523, OS:13.5, name:iPad Pro (12.9-inch) (4th generation) }
# 		{ platform:iOS Simulator, id:845E379E-3A66-42AA-A4CB-EBC666B06C59, OS:14.0, name:iPad Pro (12.9-inch) (4th generation) }
# 		{ platform:iOS Simulator, id:EB250F1A-5ADA-4F88-B6D9-06E1387AB8E0, OS:12.4, name:iPhone 5s }
# 		{ platform:iOS Simulator, id:140D155F-1CDF-43F2-9FAE-A40FD325EDB4, OS:12.4, name:iPhone 6 }
# 		{ platform:iOS Simulator, id:B2203098-F066-47D7-B127-6116B7D89A98, OS:12.4, name:iPhone 6 Plus }
# 		{ platform:iOS Simulator, id:7B0CC197-58B8-4460-88D5-8B37B9320F70, OS:12.4, name:iPhone 6s }
# 		{ platform:iOS Simulator, id:90A840EF-7E31-4ABC-B99B-326C8CFC6071, OS:12.4, name:iPhone 6s Plus }
# 		{ platform:iOS Simulator, id:618218A4-3B10-4A84-9D26-85BD01419FA5, OS:12.4, name:iPhone 7 }
# 		{ platform:iOS Simulator, id:19449422-9C01-4EF5-96AC-4127A69C3E04, OS:12.4, name:iPhone 7 Plus }
# 		{ platform:iOS Simulator, id:6996B055-3D34-4A2A-9291-0DB19B8D50D7, OS:12.4, name:iPhone 8 }
# 		{ platform:iOS Simulator, id:7CA2817D-1770-444B-9DC7-A729EF917CF4, OS:13.0, name:iPhone 8 }
# 		{ platform:iOS Simulator, id:7C6C72BD-B793-4BC9-868D-4432876236AA, OS:13.1, name:iPhone 8 }
# 		{ platform:iOS Simulator, id:557031BF-F956-4438-939E-934D088298C1, OS:13.2.2, name:iPhone 8 }
# 		{ platform:iOS Simulator, id:56DBF18B-58C5-439D-AD52-BD3EFAF47249, OS:13.3, name:iPhone 8 }
# 		{ platform:iOS Simulator, id:47140C51-0945-43A3-BCE9-D37BFE79A281, OS:13.4, name:iPhone 8 }
# 		{ platform:iOS Simulator, id:8604DB0B-06C0-427C-B5E3-5A5C31AE3B39, OS:13.5, name:iPhone 8 }
# 		{ platform:iOS Simulator, id:025CE6FD-A187-456C-AE04-05578CC04C32, OS:14.0, name:iPhone 8 }
# 		{ platform:iOS Simulator, id:64E14F5D-DD90-4FEA-87E0-96760C3E0192, OS:12.4, name:iPhone 8 Plus }
# 		{ platform:iOS Simulator, id:83ECFF27-5393-467A-93D6-CE3B823418DC, OS:13.0, name:iPhone 8 Plus }
# 		{ platform:iOS Simulator, id:032A004C-B711-4234-BBBC-3F50EA81A3CF, OS:13.1, name:iPhone 8 Plus }
# 		{ platform:iOS Simulator, id:B5960E75-AFD2-4191-AE99-587C795DB64B, OS:13.2.2, name:iPhone 8 Plus }
# 		{ platform:iOS Simulator, id:2763A277-2969-499E-91DA-2AE5BC9AA99F, OS:13.3, name:iPhone 8 Plus }
# 		{ platform:iOS Simulator, id:3142EB62-AF7B-4E68-BA98-B8FC5EE693B3, OS:13.4, name:iPhone 8 Plus }
# 		{ platform:iOS Simulator, id:060F0AC2-D744-4D78-A1EA-9A227A26ACE9, OS:13.5, name:iPhone 8 Plus }
# 		{ platform:iOS Simulator, id:C0F03144-741B-4FFD-B077-9C0FA09E4000, OS:14.0, name:iPhone 8 Plus }
# 		{ platform:iOS Simulator, id:B29C2B03-92D5-4F50-8870-2EF37623BD7A, OS:13.0, name:iPhone 11 }
# 		{ platform:iOS Simulator, id:316F7F69-B3B4-4FBC-A126-BF29AE954893, OS:13.1, name:iPhone 11 }
# 		{ platform:iOS Simulator, id:8037B054-54C5-4A58-8425-CD867D25E91A, OS:13.2.2, name:iPhone 11 }
# 		{ platform:iOS Simulator, id:E2D1DD9C-0F73-4DC3-B2A4-7359F81AEA0F, OS:13.3, name:iPhone 11 }
# 		{ platform:iOS Simulator, id:0C23F9D9-D896-422F-9B84-33DC5965BF1A, OS:13.4, name:iPhone 11 }
# 		{ platform:iOS Simulator, id:A7371C93-8CE6-47DA-934A-2D615C3BE834, OS:13.5, name:iPhone 11 }
# 		{ platform:iOS Simulator, id:F057B777-E0F0-4AD9-B765-796971A7A099, OS:14.0, name:iPhone 11 }
# 		{ platform:iOS Simulator, id:10EF563B-9DCF-45AD-83A0-AF5FA2585976, OS:13.0, name:iPhone 11 Pro }
# 		{ platform:iOS Simulator, id:1674E42D-B1E2-434D-B734-2622AF46A879, OS:13.1, name:iPhone 11 Pro }
# 		{ platform:iOS Simulator, id:00D8941E-A0C9-4970-9F76-D8D4C0E8A2C4, OS:13.2.2, name:iPhone 11 Pro }
# 		{ platform:iOS Simulator, id:D75B80EA-754A-4022-A965-DED624EEB983, OS:13.3, name:iPhone 11 Pro }
# 		{ platform:iOS Simulator, id:0D627B56-1C8D-437E-B908-C71B1F51638A, OS:13.4, name:iPhone 11 Pro }
# 		{ platform:iOS Simulator, id:AC843652-2D7E-48EF-8C74-F9E01AFBF50B, OS:13.5, name:iPhone 11 Pro }
# 		{ platform:iOS Simulator, id:51E6CE74-E3D3-43C9-8241-7D91C2D402BF, OS:14.0, name:iPhone 11 Pro }
# 		{ platform:iOS Simulator, id:0757DF55-720B-4D9A-A6D2-58BDD5B32982, OS:13.0, name:iPhone 11 Pro Max }
# 		{ platform:iOS Simulator, id:D695B0C2-A580-4B8B-893C-E0EF63AB5A99, OS:13.1, name:iPhone 11 Pro Max }
# 		{ platform:iOS Simulator, id:71D34BE5-256E-4964-90AF-285B1B5DE9DF, OS:13.2.2, name:iPhone 11 Pro Max }
# 		{ platform:iOS Simulator, id:87333B99-9813-4E0E-B49C-B4C0E2E87B8D, OS:13.3, name:iPhone 11 Pro Max }
# 		{ platform:iOS Simulator, id:71F27222-FF84-49BB-90C7-04087A57215B, OS:13.4, name:iPhone 11 Pro Max }
# 		{ platform:iOS Simulator, id:F0EDF533-EE98-403E-A111-9B4745F10476, OS:13.5, name:iPhone 11 Pro Max }
# 		{ platform:iOS Simulator, id:DD6E1455-E601-41F0-B28A-674AA401637F, OS:14.0, name:iPhone 11 Pro Max }
# 		{ platform:iOS Simulator, id:02DACC1B-A0B4-4B29-9E65-3092504F4EF6, OS:12.4, name:iPhone SE (1st generation) }
# 		{ platform:iOS Simulator, id:92A5FF5B-C03A-428D-93B5-51B41E4E2A75, OS:13.5, name:iPhone SE (2nd generation) }
# 		{ platform:iOS Simulator, id:702C4EFE-E3EE-4E67-82D4-4BF68CF660BF, OS:14.0, name:iPhone SE (2nd generation) }
# 		{ platform:iOS Simulator, id:A0215AF0-8D32-48C5-931A-36E02EBB4189, OS:12.4, name:iPhone X }
# 		{ platform:iOS Simulator, id:948AD5BF-6BC6-4B92-9F1B-BD19D0C28E70, OS:12.4, name:iPhone Xs }
# 		{ platform:iOS Simulator, id:C099E283-F9B6-4B91-9B9E-1D180F12526A, OS:12.4, name:iPhone Xs Max }
# 		{ platform:iOS Simulator, id:43D88246-7B6E-4754-BF5C-88F2A2907470, OS:12.4, name:iPhone XÊ€ }
# 		{ platform:iOS Simulator, id:CC7184C0-7944-4869-AA32-D80C7D9FF655, OS:14.0, name:iPod touch (7th generation) }
xcode_destination: platform=iOS Simulator,OS=12.4,name=iPhone 7
